### PR TITLE
Create CODEOWNERS file

### PR DESCRIPTION
**Pull request by aliculPix4D**
This PR updates the CODEOWNERS file to include an up-to-date CI members list.

**Dears Reviewers**: appreciate to ensure the PR is approved by the minimum number of required approvals

### CODE REVIEW

**Comment by marco-m-pix4d** [comment]
@aliculPix4D this PR uncovered a bug in the CI I had setup. I Need to investigate. (remember this repo is public)

**Comment by aliculPix4D** [comment]
> @aliculPix4D this PR uncovered a bug in the CI I had setup. I Need to investigate. (remember this repo is public)

I will not merge this PR, until the problem is solved.

**Comment by marco-m-pix4d** [comment]
@aliculPix4D please rebase on master after #19 is merged. It should fix the CI failures.

**Comment by marco-m-pix4d** [comment]
@aliculPix4D #19 is merged; you can go ahead.

**Pull request merged**
